# Generated by Django 4.2.3 on 2023-07-25 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=14)),
                ('tipoPessoa', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(choices=[('S', 'SAQUE'), ('D', 'DEPÓSITO'), ('T', 'TRANSFÊRENCIA'), ('E', 'EMPRÉSTIMO')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brq.cliente')),
                ('tipoTransacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brq.tipotransacao')),
            ],
        ),
    ]
