# Generated by Django 4.2.3 on 2023-07-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotransacao',
            name='descricao',
            field=models.CharField(choices=[('S', 'SAQUE'), ('D', 'DEPÓSITO'), ('T', 'TRANSFÊRENCIA'), ('E', 'EMPRÉSTIMO')], max_length=1, unique=True),
        ),
    ]
