# Generated by Django 4.2.3 on 2023-07-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brq', '0002_alter_tipotransacao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
